
# gitea with postgres

services:
  server:
    image: docker.gitea.com/gitea:1.24.4
    container_name: gitea
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_GID}
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`git.evillabs.io`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=letsencrypt
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    #  - "3000:3000" # Not required if using Traefik
      - "2222:22"
    networks:
      - gitea
      - traefik
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gitea

volumes:
  gitea:
    driver: local
  postgres:
    driver: local

networks:
  gitea:
    external: false
  traefik:
    external: true