
# gitea with postgres

services:
  gitea:
    image: docker.gitea.com/gitea:1.24.4
    container_name: gitea
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_GID}
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${HTTPS_HOSTNAME}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=letsencrypt
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    #  - "3000:3000" # Not required if using Traefik
      - "2222:22"
    networks:
      - gitea
      - traefik
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:14
    container_name: gitea-postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gitea

  gitea-runner:
    image: gitea/act_runner
    container_name: gitea-runner
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - GITEA_INSTANCE_URL=gitea:3000
      # When using Docker Secrets, it's also possible to use
      # GITEA_RUNNER_REGISTRATION_TOKEN_FILE to pass the location.
      # The env var takes precedence.
      # Needed only for the first start.
      - GITEA_RUNNER_REGISTRATION_TOKEN=<${GITEA_RUNNER_REGISTRATION_TOKEN}
    volumes:
      - runner_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
    depends_on:
      gitea:

volumes:
  gitea:
    driver: local
  postgres:
    driver: local
  runner_data:
    driver: local

networks:
  gitea:
    external: false
  traefik:
    external: true